services:
    ansible:
        container_name: control
        build:
            dockerfile: Dockerfile    
            context: ansible-control-node
            args:
                - USER=${USER}
        volumes:
            - ansible_config:/etc/ansible/
            - ansible_playbooks:/home/${USER}/playbooks/
            - persist_home:/home/${USER}
        environment:
            - USER=${USER}
        ports:
            - "2222:22"

    host-1: &base
        build:
            dockerfile: Dockerfile    
            context: regular-node
            args:
                - USER=${USER}

    host-2: 
        <<: *base

    host-3: 
        <<: *base


networks:
    default:
        name: test
        driver: bridge
    
volumes:
    persist_home:
        external: false
    
    ansible_playbooks:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./control-node/playbooks/

    ansible_config:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./control-node/ansible
    