services:
    ansible:
        container_name: control
        build:
            dockerfile: Dockerfile    
            context: ansible-control-node
            args:
                - USER=${USER}
        volumes:
            - ./control-node/ansible/:/etc/ansible/
            - persist_home:/home/${USER}
        environment:
            - USER=${USER}
        ports:
            - "2222:22"

    host-1: &base
        build:
            dockerfile: Dockerfile    
            context: regular-node
            args:
                - USER=${USER}

    host-2: 
        <<: *base

    host-3: 
        <<: *base


networks:
    default:
        name: test
        driver: bridge
    
volumes:
    persist_home:
        external: false