services:
    ansible:
        container_name: control
        hostname: control-node
        build:
            dockerfile: Dockerfile    
            context: control-node
            args:
                - USER=${USER}
        volumes:
            - ./control-node/ansible:/etc/ansible/
            - ./control-node/playbooks:/home/${USER}/playbooks/
            - persist_home:/home/${USER}
        environment:
            - USER=${USER}
        ports:
            - "2222:22"

    host-1: &base
        hostname: host-1
        ports: 
            - "80"
        build:
            dockerfile: Dockerfile    
            context: regular-node
            args:
                - USER=${USER}

    host-2: 
        hostname: host-2
        <<: *base

    host-3: 
        hostname: host-3
        <<: *base


networks:
    default:
        name: test
        driver: bridge
    
volumes:
    persist_home:
        external: false
