services:
    ansible:
        container_name: control
        build:
            dockerfile: Dockerfile    
            context: ansible-control-node
            args:
                - USER=${USER}
        volumes:
            - ./ansible-control-node/ansible/inventory:/etc/ansible/hosts
            - ./ansible-control-node/ansible/playbooks/:/etc/ansible/
            - persist_home:/home/${USER}
        environment:
            - USER=${USER}
        ports:
            - "2222:22"

    host-base: &base
        build:
            dockerfile: Dockerfile    
            context: ansible-regular-node
            args:
                - USER=${USER}
    
    host-1: 
        <<: *base

    host-2: 
        <<: *base

    host-3: 
        <<: *base


networks:
    default:
        name: test
        driver: bridge
    
volumes:
    persist_home:
        external: false